#!/bin/bash
#PBS -r n
#PBS -N Assemble409
#PBS -l walltime=100:00:00
#PBS -l procs=8
#PBS -l pmem=16000m
#!/bin/bash
file=../assemblies/WCS365
adapt=~/compbio/adapters/illumina_adapters.fa

scythe -a $adapt $file.1.fastq -o $file.scythed.1.fastq -q sanger
scythe -a $adapt $file.2.fastq -o $file.scythed.2.fastq -q sanger

sickle pe -f $file.scythed.1.fastq -r $file.scythed.2.fastq -o $file.sickled.1.fastq -p $file.sickled.2.fastq -s $file.singles.fastq -t sanger

pear -f $file.sickled.1.fastq -r $file.sickled.2.fastq -o $file -j 8

cat $file.singles.fastq $file.assembled.fastq > $file.all.singles.fastq

spades.py -m 16 -s $file.all.singles.fastq -1 $file.unassembled.forward.fastq -2 $file.unassembled.reverse.fastq --careful --cov-cutoff auto -t 8 -o $file
